const problems75 = [
  {
    Status: false,
    Title: "Two Sum",
    Solution: "https://leetcode.com/problems/two-sum/",
    Acceptance: 50,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Array", "Hash Table", "Two Pointers"],
  },
  {
    Status: false,
    Title: "Best Time to Buy and Sell Stock",
    Solution: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    Acceptance: 49,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Array", "Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Contains Duplicate",
    Solution: "https://leetcode.com/problems/contains-duplicate/",
    Acceptance: 55,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Array", "Hash Table"],
  },
  {
    Status: false,
    Title: "Product of Array Except Self",
    Solution: "https://leetcode.com/problems/product-of-array-except-self/",
    Acceptance: 59,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Prefix Sum", "Cumulative Product"],
  },
  {
    Status: false,
    Title: "Maximum Subarray",
    Solution: "https://leetcode.com/problems/maximum-subarray/",
    Acceptance: 47,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Array", "Dynamic Programming", "Kadane's Algorithm"],
  },
  {
    Status: false,
    Title: "Maximum Product Subarray",
    Solution: "https://leetcode.com/problems/maximum-product-subarray/",
    Acceptance: 32,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Find Minimum in Rotated Sorted Array",
    Solution:
      "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    Acceptance: 49,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Binary Search"],
  },
  {
    Status: false,
    Title: "Search in Rotated Sorted Array",
    Solution: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    Acceptance: 36,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Array", "Binary Search"],
  },
  {
    Status: false,
    Title: "3 Sum",
    Solution: "https://leetcode.com/problems/3sum/",
    Acceptance: 28,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Two Pointers"],
  },
  {
    Status: false,
    Title: "Container With Most Water",
    Solution: "https://leetcode.com/problems/container-with-most-water/",
    Acceptance: 51,
    Difficulty: "Medium",
    Frequency: "Low",
    Tags: ["Array", "Two Pointers"],
  },
  {
    Status: false,
    Title: "Sum of Two Integers",
    Solution: "https://leetcode.com/problems/sum-of-two-integers/",
    Acceptance: 51,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Bit Manipulation"],
  },
  {
    Status: false,
    Title: "Number of 1 Bits",
    Solution: "https://leetcode.com/problems/number-of-1-bits/",
    Acceptance: 51,
    Difficulty: "Easy",
    Frequency: "Medium",
    Tags: ["Bit Manipulation"],
  },
  {
    Status: false,
    Title: "Counting Bits",
    Solution: "https://leetcode.com/problems/counting-bits/",
    Acceptance: 69,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Bit Manipulation", "Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Missing Number",
    Solution: "https://leetcode.com/problems/missing-number/",
    Acceptance: 53,
    Difficulty: "Easy",
    Frequency: "Medium",
    Tags: ["Bit Manipulation", "Math"],
  },
  {
    Status: false,
    Title: "Reverse Bits",
    Solution: "https://leetcode.com/problems/reverse-bits/",
    Acceptance: 40,
    Difficulty: "Easy",
    Frequency: "Medium",
    Tags: ["Bit Manipulation"],
  },
  {
    Status: false,
    Title: "Climbing Stairs",
    Solution: "https://leetcode.com/problems/climbing-stairs/",
    Acceptance: 48,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Coin Change",
    Solution: "https://leetcode.com/problems/coin-change/",
    Acceptance: 35,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Longest Increasing Subsequence",
    Solution: "https://leetcode.com/problems/longest-increasing-subsequence/",
    Acceptance: 44,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Dynamic Programming", "Binary Search"],
  },
  {
    Status: false,
    Title: "Longest Common Subsequence",
    Solution: "https://leetcode.com/problems/longest-common-subsequence/",
    Acceptance: 54,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Word Break Problem",
    Solution: "https://leetcode.com/problems/word-break/",
    Acceptance: 38,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Combination Sum",
    Solution: "https://leetcode.com/problems/combination-sum/",
    Acceptance: 54,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Dynamic Programming", "Backtracking"],
  },
  {
    Status: false,
    Title: "House Robber",
    Solution: "https://leetcode.com/problems/house-robber/",
    Acceptance: 47,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "House Robber II",
    Solution: "https://leetcode.com/problems/house-robber-ii/",
    Acceptance: 36,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Decode Ways",
    Solution: "https://leetcode.com/problems/decode-ways/",
    Acceptance: 27,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Unique Paths",
    Solution: "https://leetcode.com/problems/unique-paths/",
    Acceptance: 53,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Jump Game",
    Solution: "https://leetcode.com/problems/jump-game/",
    Acceptance: 37,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Greedy", "Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Clone Graph",
    Solution: "https://leetcode.com/problems/clone-graph/",
    Acceptance: 41,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Depth-First Search", "Breadth-First Search", "Graph"],
  },
  {
    Status: false,
    Title: "Course Schedule",
    Solution: "https://leetcode.com/problems/course-schedule/",
    Acceptance: 43,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
  },
  {
    Status: false,
    Title: "Pacific Atlantic Water Flow",
    Solution: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    Acceptance: 43,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Depth-First Search", "Breadth-First Search", "Graph"],
  },
  {
    Status: false,
    Title: "Number of Islands",
    Solution: "https://leetcode.com/problems/number-of-islands/",
    Acceptance: 51,
    Difficulty: "Medium",
    Frequency: "Low",
    Tags: ["Depth-First Search", "Breadth-First Search", "Union Find", "Graph"],
  },
  {
    Status: false,
    Title: "Longest Consecutive Sequence",
    Solution: "https://leetcode.com/problems/longest-consecutive-sequence/",
    Acceptance: 45,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Array", "Union Find"],
  },
  {
    Status: false,
    Title: "Alien Dictionary",
    Solution: "https://leetcode.com/problems/alien-dictionary/",
    Acceptance: 32,
    Difficulty: "Hard",
    Frequency: "Low",
    Tags: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
  },
  {
    Status: false,
    Title: "Graph Valid Tree",
    Solution: "https://leetcode.com/problems/graph-valid-tree/",
    Acceptance: 42,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Depth-First Search", "Breadth-First Search", "Graph", "Union Find"],
  },
  {
    Status: false,
    Title: "Number of Connected Components in an Undirected Graph",
    Solution:
      "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    Acceptance: 55,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Depth-First Search", "Breadth-First Search", "Graph", "Union Find"],
  },
  {
    Status: false,
    Title: "Insert Interval",
    Solution: "https://leetcode.com/problems/insert-interval/",
    Acceptance: 34,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Array", "Sort", "Interval"],
  },
  {
    Status: false,
    Title: "Merge Intervals",
    Solution: "https://leetcode.com/problems/merge-intervals/",
    Acceptance: 40,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Sort", "Interval"],
  },
  {
    Status: false,
    Title: "Non-overlapping Intervals",
    Solution: "https://leetcode.com/problems/non-overlapping-intervals/",
    Acceptance: 45,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Greedy", "Interval"],
  },
  {
    Status: false,
    Title: "Meeting Rooms",
    Solution: "https://leetcode.com/problems/meeting-rooms/",
    Acceptance: 57,
    Difficulty: "Easy",
    Frequency: "Medium",
    Tags: ["Array", "Sort", "Interval"],
  },
  {
    Status: false,
    Title: "Meeting Rooms II",
    Solution: "https://leetcode.com/problems/meeting-rooms-ii/",
    Acceptance: 47,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Heap", "Greedy", "Interval"],
  },
  {
    Status: false,
    Title: "Reverse a Linked List",
    Solution: "https://leetcode.com/problems/reverse-linked-list/",
    Acceptance: 72,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Linked List"],
  },
  {
    Status: false,
    Title: "Detect Cycle in a Linked List",
    Solution: "https://leetcode.com/problems/linked-list-cycle/",
    Acceptance: 42,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Linked List", "Two Pointers"],
  },
  {
    Status: false,
    Title: "Merge Two Sorted Lists",
    Solution: "https://leetcode.com/problems/merge-two-sorted-lists/",
    Acceptance: 57,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Linked List"],
  },
  {
    Status: false,
    Title: "Merge k Sorted Lists",
    Solution: "https://leetcode.com/problems/merge-k-sorted-lists/",
    Acceptance: 42,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Linked List", "Heap", "Divide and Conquer"],
  },
  {
    Status: false,
    Title: "Remove Nth Node From End of List",
    Solution: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    Acceptance: 37,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Linked List", "Two Pointers"],
  },
  {
    Status: false,
    Title: "Reorder List",
    Solution: "https://leetcode.com/problems/reorder-list/",
    Acceptance: 39,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Linked List"],
  },
  {
    Status: false,
    Title: "Set Matrix Zeroes",
    Solution: "https://leetcode.com/problems/set-matrix-zeroes/",
    Acceptance: 42,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array"],
  },
  {
    Status: false,
    Title: "Spiral Matrix",
    Solution: "https://leetcode.com/problems/spiral-matrix/",
    Acceptance: 37,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array"],
  },
  {
    Status: false,
    Title: "Rotate Image",
    Solution: "https://leetcode.com/problems/rotate-image/",
    Acceptance: 59,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array"],
  },
  {
    Status: false,
    Title: "Word Search",
    Solution: "https://leetcode.com/problems/word-search/",
    Acceptance: 36,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Array", "Backtracking"],
  },
  {
    Status: false,
    Title: "Longest Substring Without Repeating Characters",
    Solution:
      "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    Acceptance: 30,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Hash Table", "Two Pointers", "String", "Sliding Window"],
  },
  {
    Status: false,
    Title: "Longest Repeating Character Replacement",
    Solution:
      "https://leetcode.com/problems/longest-repeating-character-replacement/",
    Acceptance: 46,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Two Pointers", "Sliding Window", "String"],
  },
  {
    Status: false,
    Title: "Minimum Window Substring",
    Solution: "https://leetcode.com/problems/minimum-window-substring/",
    Acceptance: 32,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Hash Table", "Two Pointers", "String", "Sliding Window"],
  },
  {
    Status: false,
    Title: "Valid Anagram",
    Solution: "https://leetcode.com/problems/valid-anagram/",
    Acceptance: 61,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Hash Table", "Sort"],
  },
  {
    Status: false,
    Title: "Group Anagrams",
    Solution: "https://leetcode.com/problems/group-anagrams/",
    Acceptance: 58,
    Difficulty: "Medium",
    Frequency: "Low",
    Tags: ["Hash Table", "String"],
  },
  {
    Status: false,
    Title: "Valid Parentheses",
    Solution: "https://leetcode.com/problems/valid-parentheses/",
    Acceptance: 40,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Stack", "String"],
  },
  {
    Status: false,
    Title: "Valid Palindrome",
    Solution: "https://leetcode.com/problems/valid-palindrome/",
    Acceptance: 38,
    Difficulty: "Easy",
    Frequency: "Medium",
    Tags: ["Two Pointers", "String"],
  },
  {
    Status: false,
    Title: "Longest Palindromic Substring",
    Solution: "https://leetcode.com/problems/longest-palindromic-substring/",
    Acceptance: 30,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["String", "Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Palindromic Substrings",
    Solution: "https://leetcode.com/problems/palindromic-substrings/",
    Acceptance: 64,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["String", "Dynamic Programming"],
  },
  {
    Status: false,
    Title: "Encode and Decode Strings",
    Solution: "https://leetcode.com/problems/encode-and-decode-strings/",
    Acceptance: 47,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["String"],
  },
  {
    Status: false,
    Title: "Maximum Depth of Binary Tree",
    Solution: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    Acceptance: 68,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Tree", "Depth-First Search", "Breadth-First Search"],
  },
  {
    Status: false,
    Title: "Same Tree",
    Solution: "https://leetcode.com/problems/same-tree/",
    Acceptance: 55,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Tree", "Depth-First Search", "Breadth-First Search"],
  },
  {
    Status: false,
    Title: "Invert/Flip Binary Tree",
    Solution: "https://leetcode.com/problems/invert-binary-tree/",
    Acceptance: 68,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Tree", "Depth-First Search", "Breadth-First Search"],
  },
  {
    Status: false,
    Title: "Binary Tree Maximum Path Sum",
    Solution: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    Acceptance: 35,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Tree", "Depth-First Search"],
  },
  {
    Status: false,
    Title: "Binary Tree Level Order Traversal",
    Solution:
      "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    Acceptance: 55,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Tree", "Breadth-First Search"],
  },

  {
    Status: false,
    Title: "Serialize and Deserialize Binary Tree",
    Solution:
      "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    Acceptance: 52,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Tree", "Design"],
  },
  {
    Status: false,
    Title: "Subtree of Another Tree",
    Solution: "https://leetcode.com/problems/subtree-of-another-tree/",
    Acceptance: 44,
    Difficulty: "Easy",
    Frequency: "Medium",
    Tags: ["Tree", "Depth-First Search"],
  },
  {
    Status: false,
    Title: "Construct Binary Tree from Preorder and Inorder Traversal",
    Solution:
      "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    Acceptance: 49,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Tree", "Depth-First Search"],
  },
  {
    Status: false,
    Title: "Validate Binary Search Tree",
    Solution: "https://leetcode.com/problems/validate-binary-search-tree/",
    Acceptance: 28,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Tree", "Depth-First Search"],
  },
  {
    Status: false,
    Title: "Kth Smallest Element in a BST",
    Solution: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    Acceptance: 59,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Tree", "Depth-First Search", "Binary Search"],
  },
  {
    Status: false,
    Title: "Lowest Common Ancestor of BST",
    Solution:
      "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    Acceptance: 47,
    Difficulty: "Easy",
    Frequency: "High",
    Tags: ["Tree", "Depth-First Search"],
  },
  {
    Status: false,
    Title: "Implement Trie (Prefix Tree)",
    Solution: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    Acceptance: 49,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Design", "Trie"],
  },
  {
    Status: false,
    Title: "Add and Search Word",
    Solution:
      "https://leetcode.com/problems/add-and-search-word-data-structure-design/",
    Acceptance: 33,
    Difficulty: "Medium",
    Frequency: "Medium",
    Tags: ["Design", "Trie"],
  },
  {
    Status: false,
    Title: "Word Search II",
    Solution: "https://leetcode.com/problems/word-search-ii/",
    Acceptance: 34,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Backtracking", "Trie"],
  },
  {
    Status: false,
    Title: "Merge K Sorted Lists",
    Solution: "https://leetcode.com/problems/merge-k-sorted-lists/",
    Acceptance: 42,
    Difficulty: "Hard",
    Frequency: "Medium",
    Tags: ["Linked List", "Heap", "Divide and Conquer"],
  },
  {
    Status: false,
    Title: "Top K Frequent Elements",
    Solution: "https://leetcode.com/problems/top-k-frequent-elements/",
    Acceptance: 60,
    Difficulty: "Medium",
    Frequency: "High",
    Tags: ["Hash Table", "Heap"],
  },
];
console.log(problems75.length);
